
#version: 1.0.{build}-{branch}
version: "{build}-{branch}"

environment:
  matrix:
    - RUBY_VERSION: 193
    - RUBY_VERSION: 24
    - RUBY_VERSION: 193
      TZONE: "Coordinated Universal Time"
    - RUBY_VERSION: 24
      TZONE: "Coordinated Universal Time"
    - RUBY_VERSION: 193
      TZONE: "Tokyo Standard Time"
    - RUBY_VERSION: 24
      TZONE: "Tokyo Standard Time"
    - RUBY_VERSION: 193
      TZONE: "Eastern Standard Time"
    - RUBY_VERSION: 24
      TZONE: "Eastern Standard Time"

install:
  - tzutil /s "%TZONE%"
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cp Gemfile.appveyor Gemfile
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec

